// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9nFQG1vRyMLfuK_xJGcNfKYqv0WM_5qQ',
    appId: '1:442090119862:web:2e84beb50647b4944cfc17',
    messagingSenderId: '442090119862',
    projectId: 'flutterchatfirebase1',
    authDomain: 'flutterchatfirebase1.firebaseapp.com',
    storageBucket: 'flutterchatfirebase1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk7ttMQPHsN8dL9fXWVb-K6ktV_sVhLns',
    appId: '1:442090119862:android:37eaf6d9b993d82d4cfc17',
    messagingSenderId: '442090119862',
    projectId: 'flutterchatfirebase1',
    storageBucket: 'flutterchatfirebase1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY-znWBv7sORCI1xkxTu4E-bUCACmCMeE',
    appId: '1:442090119862:ios:fcfd07b49d2eb93d4cfc17',
    messagingSenderId: '442090119862',
    projectId: 'flutterchatfirebase1',
    storageBucket: 'flutterchatfirebase1.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
